config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"

  get '/petition', to: 'home#petition'
  get '/about', to: 'home#about'
  get '/faq', to: 'home#faq'
  get '/resolution', to: 'home#resolution'
  get '/admin', to: 'admin#index'
  get '/signup', to: 'home#googleform'

  resources :organizations
  resources :articles
  resources :files
end

app/models/article.rb
class Article < ActiveRecord::Base
end

app/models/organization.rb
class Organization < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authenticate_user!

  def index
    @organizations = Organization.all.order(:name)
    @articles = Article.select{|article| article.articleType != "File"}
    @files = Article.select{|article| article.articleType == "File"}
    @user = current_user
  end

  def new
    @article = Article.new
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!

  def index
    @user = current_user
    @articles = Article.select{|article| article.articleType != "File"}
    @press = @articles.select {|article| article.articleType == "Press"}
    @coalition = @articles.select {|article| article.articleType == "Coalition"}
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.create!(article_params)
    if @article.articleType != "File"
      @date = @article.date
      @date.strftime("%B %e, %Y")
      redirect_to articles_path
    elsif @article.articleType == "File"
      @article.update( date: Time.now.strftime("%B %e, %Y") )
      redirect_to files_path
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    @article.update(article_params)
    redirect_to articles_path
  end

  def destroy
    @article = Article.find(params[:id])
    if @article.articleType != "File"
      @article.destroy
      redirect_to articles_path
    elsif @article.articleType == "File"
      @article.destroy
      redirect_to files_path
    end
  end

  private
    def article_params
      params.require(:article).permit(:date, :title, :source, :articleType, :url)
    end

end

app/controllers/files_controller.rb
class FilesController < ApplicationController
  before_action :authenticate_user!

  def index
    @user = current_user
    @files = Article.select{|article| article.articleType == "File"}
  end

  def new
    @article = Article.new
  end

  def create
    @file = Article.create!(file_params)
    @file.update( articleType: "File" )
    @file.update( date: Time.now.strftime("%B %e, %Y") )
    redirect_to files_path
  end

  def destroy
    @file = Article.find(params[:id])
    @file.destroy
    redirect_to files_path
  end

  private
    def file_params
      params.require(:article, :url).permit(:date, :title, :source, :articleType)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @organizations = Organization.all.order(:name)
    @articles = Article.all.order(:date).reverse
    @press = @articles.select {|article| article.articleType == "Press"}
    @coalition = @articles.select {|article| article.articleType == "Coalition"}
  end

  def resolution
    @files = Article.select{|article| article.articleType == "File"}
  end

end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_action :authenticate_user!

  def index
    @user = current_user
    @organizations = Organization.all.order(:name)
  end

  def show
    @organization = Organization.find(params[:id])
  end

  def new
    @organization = Organization.new
  end

  def create
    @organization = Organization.create!(org_params)
    redirect_to organizations_path
  end

  def edit
    @organization = Organization.find(params[:id])
  end

  def update
    @organization = Organization.find(params[:id])
    @organization.update(org_params)
    redirect_to organizations_path
  end

  def destroy
    @organization = Organization.find(params[:id])
    @organization.destroy
    redirect_to organizations_path
  end

  private
    def org_params
      params.require(:organization).permit(:name, :orgtype, :orgUrl)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/index.html.erb
<% if current_user %>
<div>
  <h3>Welcome, <%= @user.email %>!</h3>
  <%= link_to "Sign Out", destroy_user_session_path, :method => :delete, :class => "btn btn-danger" %>
</div>
<% end %>
<div class="row admin-portal-main">
  <h2>DC Fair Elections Coalition</h2>
  <h3>Administration Portal</h3>

  <div class="col-md-4 col-xs-12 orgs">
    <h3>Coalition Member Management</h3>
    <div class="orgs-count">
      Number of Coalition Members: <%= @organizations.count %>
    </div>
    <%= link_to "View List", organizations_path, :class => "btn btn-lg btn-primary" %>
    <%= link_to "Add New Member", new_organization_path, :class => "btn btn-lg btn-danger" %>
  </div>

  <div class="col-md-4 col-xs-12 news">
    <h3>News Section Management</h3>
    <div class="news-count">
      Number of Items: <%= @articles.count %>
    </div>
    <%= link_to "View List", articles_path, :class => "btn btn-lg btn-primary" %>
    <%= link_to "Add New Item", new_article_path, :class => "btn btn-lg btn-danger" %>
  </div>

  <div class="col-md-4 col-xs-12 files">
    <h3>Files Management</h3>
    <div class="files-count">
      Number of Items: <%= @files.count %>
    </div>
      <%= link_to "View List", files_path, :class => "btn btn-lg btn-primary" %>
      <%= link_to "Add New File", new_file_path, :class => "btn btn-lg btn-danger" %>
  </div>
</div>

app/views/articles/_newarticle.html.erb
<%= form_for ([@article]) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title, :placeholder => "Title" %>

  <%= f.label :date, "Article Date" %>
  <%= f.text_field :date, :placeholder => "yyyy-mm-dd", :class => "datepicker" %>

  <%= f.label :source, "News Outlet/Organization" %>
  <%= f.text_field :source, :placeholder => "eg Washington Post" %>

  <div class="article-type">
    <h4>Press Hit or Internal Source?</h4>
    <%= f.radio_button :articleType, "Press" %>
    <%= f.label :articleType, "Press", :value => "press" %>
    <%= f.radio_button :articleType, "Coalition" %>
    <%= f.label :articleType, "Coalition", :value => "coalition" %>
  </div>

  <%= f.label :url, "Article Link" %>
  <%= f.text_field :url, :placeholder => "Ex: http://organization.com/article-xyz" %>

  <%= f.submit %>
<% end %>

app/views/articles/edit.html.erb
<div class="article-edit-page">
  <h2>Add News Item</h2>
  <h3><%= link_to "Back to Articles List", articles_path %></h3>

  <div class="form">
    <%=render 'newarticle' %>
  </div>

</div>

app/views/articles/index.html.erb
<% if current_user %>
<div>
  <h3>Welcome, <%= @user.email %>!</h3>
  <%= link_to "Sign Out", destroy_user_session_path, :method => :delete, :class => "btn btn-danger" %>
  <%= link_to "Back to Admin Portal", "/admin", :class => "btn btn-primary" %>
</div>
<% end %>

<h2>List of Coalition News Articles</h2>
<%= link_to "Add New Article", new_article_path, :class => "btn btn-lg btn-primary" %>

<div class="col-md-12">
  <h3>Press Coverage</h3>
  <div class="row">
    <ul class="admin-article-list">
      <% @press.each do |item| %>
      <li class="row each">
        <div class="col-md-8 col-xs-12">
          <div><%= link_to item.title, item.url, :target => "_blank" %></div>
          <div><strong>Source:</strong> <%= item.source %>; <strong>Date:</strong> <%= item.date.strftime("%B %e, %Y") %>
          </div>
        </div>
        <div class="col-md-4 col-xs-12 admin-edit-delete">
          <div class="edit">
            <%= link_to "Edit Article Info", edit_article_path(item), :class => "btn btn-sm btn-default" %>
          </div>
          <div class="delete">
            <%= form_for(item, method: :delete) do |f| %>
              <%= f.submit "Delete Article", :class => "btn btn-sm btn-danger" %>
            <% end %>
          </div>
        </div>
      </li>
      <% end %>
      <!-- <li><a href="https://wamu.org/news/15/12/01/proposal_seeks_to_weaken_special_interests_influence_over_dc_elections" target="_blank">Proposal Seeks To Weaken Special Interests' Influence Over D.C. Elections</a><br/ >WAMU, December 1</li>
      <li><a href="https://www.washingtonpost.com/opinions/the-sudden-end-of-freshpac/2015/11/13/f8ce5b60-88c6-11e5-bd91-d385b244482f_story.html" target="_blank">The sudden end of FreshPAC</a><br/ >Washington Post LTE, November 13</li>
      <li><a href="https://www.washingtonpost.com/local/dc-council-to-consider-public-financing-of-campaigns/2015/12/01/e67af82e-985c-11e5-aca6-1ae3be6f06d2_story.html" target="_blank">DC Council to consider public financing of campaigns</a><br/ >Associated Press, December 1</li>
      <li><a href="http://thekojonnamdishow.org/shows/2015-12-01/u-s-rep-john-sarbanes-on-how-money-influences-politics-locally-and-nationally" target="_blank">U.S. Rep. John Sarbanes On How Money Influences Politics, Locally And Nationally</a><br/ >The Kojo Nnamdi Show, WAMU 88.5, December 1</li> -->
    </ul>
  </div>
</div>

<div class="col-md-12">
  <h3>Coalition Partner Releases</h3>
  <div class="row">
    <ul class="admin-article-list">
      <% @coalition.each do |item| %>
      <li class="row each">
        <div class="col-md-8 col-xs-12">
          <div><%= link_to item.title, item.url, :target => "_blank" %></div>
          <div><strong>Source:</strong> <%= item.source %>; <strong>Date:</strong> <%= item.date.strftime("%B %e, %Y") %>
          </div>
        </div>
        <div class="col-md-4 col-xs-12 admin-edit-delete">
          <div class="edit">
            <%= link_to "Edit Article Info", edit_article_path(item), :class => "btn btn-sm btn-default" %>
          </div>
          <div class="delete">
            <%= form_for(item, method: :delete) do |f| %>
              <%= f.submit "Delete Article", :class => "btn btn-sm btn-danger" %>
            <% end %>
          </div>
        </div>
      </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/articles/new.html.erb
<div class="article-new-page">
<h2>Add News Item</h2>
<h3><%= link_to "Back to Articles List", articles_path %></h3>

<div class="form">
  <%=render 'newarticle' %>
</div>

</div>

app/views/files/_newfile.html.erb
<%= form_for ([@article]) do |f| %>
  <%= f.label :title, "Document Name" %>
  <%= f.text_field :title %>

  <%= f.label :source, "Document Description" %>
  <%= f.text_area :source %>

  <%= f.label :url, "File Link" %>
  <%= f.text_field :url, :placeholder => "Ex: http://organization.com/file-xyz" %>

  <%= f.hidden_field :articleType, :value => "File" %>

  <%= f.submit "Create File"%>
<% end %>

app/views/files/edit.html.erb
<div class="file-edit-page">
  <h2>Add News Item</h2>
  <h3><%= link_to "Back to Files List", files_path %></h3>

  <div class="form">
    <%=render 'newfile' %>
  </div>

</div>

app/views/files/index.html.erb
<% if current_user %>
<div>
  <h3>Welcome, <%= @user.email %>!</h3>
  <%= link_to "Sign Out", destroy_user_session_path, :method => :delete, :class => "btn btn-danger" %>
  <%= link_to "Back to Admin Portal", "/admin", :class => "btn btn-primary" %>
</div>
<% end %>


<h2>List of Files for Download</h2>
<%= link_to "Add New File", new_file_path, :class => "btn btn-lg btn-primary" %>

<div class="col-md-12">
  <div class="row">
    <ul class="admin-file-list">
      <% @files.each do |item| %>
      <li class="row each">
        <div class="col-md-8 col-xs-12">
          <div><h4><%= link_to item.title, item.url, :target => "_blank" %></h4></div>
          <div><strong>Description:</strong> <%= item.source %><strong><br>Date Uploaded:</strong> <%= item.date.strftime("%B %e, %Y") %>
          </div>
        </div>
        <div class="col-md-4 col-xs-12 admin-edit-delete">
          <div class="edit">
            <%= link_to "Edit File Info", edit_file_path(item), :class => "btn btn-sm btn-default" %>
          </div>
          <div class="delete">
            <%= form_for(item, method: :delete) do |f| %>
              <%= f.submit "Delete File", :class => "btn btn-sm btn-danger" %>
            <% end %>
          </div>
        </div>
      </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/files/new.html.erb
<div class="file-new-page">
<h2>Add News Item</h2>
<h3><%= link_to "Back to Files List", files_path %></h3>

<div class="form">
  <%=render 'newfile' %>
</div>

</div>

app/views/home/_action.html.erb
<h2>Fair Elections DC Action Hub</h2>
<div class="row" id="petition">
  <h3>Sign the Official Coalition Petition!</h3>
  <h4>Become a Citizen Co-Sponsor of B21-0509, the Citizens Fair Election Program Amendment Act of 2015</h4>
  <%= render 'petition' %>
</div>

<div class="row" id="letter">
  <h3>DC Residents: Send an E-mail to Your Councilmembers!</h3>
  <%= render 'letter' %>
</div>

app/views/home/_coalition.html.erb
<div class="col-md-12">
  <h2>DC Fair Elections Coalition</h2>
  <h5>The DC Fair Elections Coalition represents groups from the environmental, labor, economic justice, social justice, faith, and good government movements. Our mission is to pass meaningful campaign finance reform in D.C. to empower everyday residents and make sure every voice is heard in our democracy.</h5>
  <div class="coalition-join">
  <h4>Run an Organization?</h4>
  <a href="mailto:zweinstein@pirg.org" class="btn btn-info" id="coalition-contact-btn">E-mail Us to Learn More</a>
</div>
  <h3>Coalition Members</h3>
  <ul class="coalition-orgs">
    <% @organizations.in_groups_of(28, false) do |org_col| %>
    <div class="col-md-4 col-xs-12">
      <% org_col.each do |org| %>
      <li>
        <% if org.orgUrl %>
          <a href='<%= org.orgUrl %>' target="_blank"><%= org.name %></a>
        <% else %>
          <%= org.name %>
        <% end %>
      </li>
      <% end %>
    </div>
    <% end %>
  </ul>
</div>

<!-- <div class="col-md-3 col-xs-6">
  <h3>Other Local Organizations</h3>
  <ul class="coalition-orgs coalition-orgs-community">
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
  </ul>
</div>
<div class="col-md-3 col-xs-6">
  <h3>National Organizations</h3>
  <ul class="coalition-orgs coalition-orgs-national">
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
  </ul>
</div>
<div class="col-md-3 col-xs-6">
  <h3>Individuals</h3>
  <ul class="coalition-orgs coalition-orgs-people">
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
  </ul>
</div> -->

app/views/home/_letter.html.erb
<!-- <div class="col-md-12 letter-button">
  <button type="button" class="btn btn-info btn-lg" id="showLetter"><span class="glyphicon glyphicon-email"></span> E-mail Your Councilmembers</button>
</div> -->

<div class="col-md-12 col-xs-12" id="letterIntro">
  <div class="well text-justify">
    <p>The bill already has strong support in the Council and stands a real chance of passing this spring, but first it needs to make it through the Judiciary Committee. And to do that, we need a hearing on the bill.</p>
    <p>Using the form below, please take a moment to send an email your councilmembers and urge them to request a hearing in the Judiciary Committee.</p>
  </div>
</div>

<div class="col-md-12 col-xs-12">
  <link href='https://actionnetwork.org/css/style-embed-whitelabel.css' rel='stylesheet' type='text/css' />
  <script>window.yepnope || document.write('<script src="https://actionnetwork.org/includes/js/yepnope154-min.js"><\/script>');</script>
  <script src='https://actionnetwork.org/widgets/v2/letter/support-b21-0509-the-fair-election-program-amendment-act-of-2015?format=js&source=widget'></script>
  <div id='can-letter-area-support-b21-0509-the-fair-election-program-amendment-act-of-2015' style='width: '><!-- this div is the target for our HTML insertion -->
  </div>
</div>

app/views/home/_petition.html.erb
<div class="col-md-12 petition-button">
  <button type="button" class="btn btn-info btn-lg" id="showPetition">Show Petition Text</button>
</div>
<div class="col-md-12 col-xs-12" id="petitionDetail">
  <div class="well">
    <h2>Petition to the DC Council</h2>
    <h3>Sponsored by the DC Fair Elections Coalition</h3>
    <div class="text-justify">
      <p>We the undersigned support the enactment of a small donor campaign financing program in the District of Columbia that matches small contributions with limited public funds to candidates who voluntarily forgo large and corporate contributions. Such a system would fight the influence of big money, empower everyday D.C. residents, and make sure every voter’s voice matters in our elections.</p>
      <p>Our democracy works best when it lives up to the principle of one person, one vote, and when the strength of a citizen’s voice doesn’t depend on the size of their wallet.  Yet in the last few years, we have seen the voices of everyday citizens increasingly drowned out by a flood of big money, and elected officials at all levels of government become increasingly dependent on large donors and Super PAC backing.</p>
      <p>In the 2012 election, it took just the top 32 donors to Super PACs, giving an average of $9.9 million each, to contribute as much as all 3.7 million small donors to President Obama and Mitt Romney combined. Here in D.C., candidates for office too often must depend on wealthy donors who can give far more than the average D.C. resident can afford.</p>
      <p>Fortunately, there are solutions within reach that can be implemented in the District to reclaim our democracy from overdependence on big money. As the District becomes more affluent, it is critical that candidates are rewarded for focusing their campaign on city residents of all means. Small donor empowerment programs put voters back in the driver’s seat of our elections by matching contributions as small as $5 to candidates who qualify with limited public funds. This system would allow candidates relying on small donors to compete with big money candidates. Instead of dialing for dollars in search of the biggest checks, candidates could fund their campaigns by appealing to everyday constituents.</p>
      <p>The track record of small donor systems is impressive. In New York City, where small contributions are matched at a six-to-one ratio, small donors of all means have played an increasingly meaningful role in funding campaigns. For example, in the 2013 city council race, participating candidates got 61 percent of their contributions from small donations and matching funds. That year, 92 percent of candidates running in the primary participated in the program. The potential of such programs is one reason why other states and localities have adopted or are considering enacting them. Small donor public financing programs have been successful in Connecticut, Arizona, and Maine, and other cities like Los Angeles. In the fall of 2014, neighboring Montgomery County, Md., became the latest jurisdiction to create a small donor empowerment program.</p>
      <p>The problem of big money dominance is clear to DC residents, who have witnessed one campaign finance scandal after another. Polling has shown that Americans from across the political spectrum think that special interest groups, lobbyists, and campaign contributors have the most influence over how their representatives vote. It is time to demonstrate support for solutions to reclaim our democracy for the people. We urge you to stand up for the voices of your constituents by supporting the enactment of a small donor campaign financing program in the District of Columbia.</p>
    </div>
  </div>
</div>
<div class="col-md-12 col-xs-12">
  <link href='https://actionnetwork.org/css/style-embed-whitelabel.css' rel='stylesheet' type='text/css' />
  <script>window.yepnope || document.write('<script src="https://actionnetwork.org/includes/js/yepnope154-min.js"><\/script>');</script>
  <script src='https://actionnetwork.org/widgets/v2/petition/support-small-donor-democracy-in-dc?format=js&source=widget'></script>
  <div id='can-petition-area-support-small-donor-democracy-in-dc' style='width:100%'>
    <!-- this div is the target for our HTML insertion -->
  </div>
</div>

app/views/home/_signup.html.erb
<iframe class="google-form" src="https://docs.google.com/forms/d/e/1FAIpQLSdcJQyVcji31X-VjnMiLLQ8uQHk15FDc3Jq5mS-NPM-9_fMbA/viewform?embedded=true" width="760" height="500" frameborder="0" marginheight="0" marginwidth="0">Loading...</iframe>

app/views/home/googleform.html.erb
<div id="google-form-signup" class="page-signup">
  <%= render 'signup' %>
</div>
<div class="home-link-button text-center">
  <a class="btn btn-danger btn-lg" href="/">Back to Home Page</a>
</div>

app/views/home/index.html.erb
<div id="home">
  <div class="row section">
    <div class="col-md-12">
      <h1>DC Fair Elections Coalition</h1>
      <h2>Reclaiming our Democracy in the District of Columbia</h2>
    </div>

    <div class="col-md-12">
      <div id="homeCarousel" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
          <li data-target="#homeCarousel" data-slide-to="0" class="active"></li>
          <li data-target="#homeCarousel" data-slide-to="1"></li>
          <li data-target="#homeCarousel" data-slide-to="2"></li>
        </ol>

        <div class="carousel-inner" role="listbox">
          <div class="item active">
            <a href="/about">
              <%= image_tag("carousel_1.png", alt: "About Fair Elections")%>
              <div class="carousel-caption">
                <h2>About Small-Donor Democracy</h2>
                <p>Learn about the movement for fair elections, why it matters here, and the bill in DC Council.</p>
              </div>
            </a>
          </div>
          <div class="item">
            <a href="#homePetition">
              <%= image_tag("carousel_2.png", alt: "Get Involved")%>
              <div class="carousel-caption">
                <h2>Get Involved</h2>
                <p>Take action to support the Citizens Fair Election Program Amendment Act of 2015.</p>
              </div>
            </a>
          </div>
          <div class="item">
            <a href="#coalition">
              <%= image_tag("launch.png", alt: "About the Coalition")%>
              <div class="carousel-caption">
                <h2>About the Fair Elections Coalition</h2>
                <p>The coalition is led by a mix of local and national grassroots organizations and their members.</p>
              </div>
            </a>
          </div>
        </div>
          <!-- Left and right controls -->
        <a class="left carousel-control" href="#homeCarousel" role="button" data-slide="prev">
          <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#homeCarousel" role="button" data-slide="next">
          <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
    </div>


    <div class="summary-sections">
      <div class="col-md-6 col-xs-12">
        <div class="well" id="aboutSummary">
          <h3>Fair Elections Legislation</h3>
          <h4>Highlights of Small Donor Empowerment Legislation in DC:</h4>
          <ul>
            <!-- <li>Introduced on December 1, 2015, as B21-0509, the "Citizens Fair Election Program Amendment Act of 2015".</li>
            <li>Introduced by Councilmember David Grosso</li>
            <li>Co-sponsored by Chairman Phil Mendelson and Councilmembers Charles Allen, Mary Cheh, Brianne Nadeau, and Elissa Silverman.</li> -->
            <li>Would cover the offices of Mayor, City Council, and Attorney General.</li>
            <li>Participating candidates qualify for the program by collecting a certain number of contributions of $100 or less from DC residents.</li>
            <li>The program provides a base grant to qualifying candidates and a 5:1 public match on all subsequent eligible contributions.</li>
            <li>Participating candidates cannot accept contributions larger than $100 and cannot coordinate with independent expenditure committees.</li>
            <li>The total amount of matching funds a candidate can receive is capped based on the average cost of recent winning campaigns for that office.</li>
          </ul>
          <!-- <button class="btn btn-primary btn-lg"><%= link_to "Learn More", "#about" %></button> -->
          <button class="btn btn-primary btn-lg"><%= link_to "Become a Citizen Co-Sponsor", "#homePetition" %></button>
        </div>
        <div class="well" id="whySummary">
          <h3>Why Fair Elections?</h3>
          <h4>What this legislation would do for DC:</h4>
          <ul>
            <li>Make D.C. elected officials more accountable to D.C. residents.</li>
            <li>Give candidates a way to fund their campaigns by motivating supporters in the communities they serve, rather than high-dollar donors looking for a sweetheart deal in return.</li>
            <li>Provide a bullhorn to ensure the voices of everyday citizens are continually heard in the Wilson Building.</li>
            <li>Increase the range of choices by giving grassroots-oriented candidates a means to get their message out.</li>
          </ul>
          <button class="btn btn-primary btn-lg"><%= link_to "Learn More", "/about" %></button>
        </div>
      </div>

      <div class="col-md-6 col-xs-12">

        <div class="well" id="google-form-signup">
          <%= render 'signup' %>
        </div>
        <div class="well" id="newsSummary">
          <h3>Recent News</h3>
          <h4>Press Coverage</h4>
          <ul>
            <% @press.each do |item| %>
            <li>
              <div><%= link_to item.title, item.url, :target => "_blank" %></div>
              <div><%= item.source %>, <%= item.date.strftime("%B %e, %Y") %></div>
            </li>
            <% end %>
          </ul>
          <h4>Coalition Partner Releases</h4>
          <ul>
            <% @coalition.each do |item| %>
            <li>
              <div><%= link_to item.title, item.url, :target => "_blank" %></div>
              <div><%= item.source %>, <%= item.date.strftime("%B %e, %Y") %></div>
            </li>
            <% end %>
          </ul>
          <!-- <button class="btn btn-primary btn-lg"><%= link_to "See All News", "#news" %></button> -->
        </div>
      </div>
    </div>
  </div>

  <div class="row section" id="homePetition">
    <div class="row" id="action">
      <%= render 'action' %>
    </div>
  </div>
<!--

<div class="row" id="news">
  <%= render 'news' %>
</div> -->

<div class="row section" id="coalition">
  <%= render 'coalition' %>
</div>

<!-- <div class="row" id="contact">
  <%= render 'contact' %>
</div> -->

app/views/organizations/_neworg.html.erb
<%= form_for ([@organization]) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, :placeholder => "Org Name" %>

  <%= f.label :orgtype, "Type" %>
  <%= f.text_field :orgtype, :placeholder => "Local/National/etc" %>

  <%= f.label :orgUrl, "Organization Link" %>
  <%= f.text_field :orgUrl, :placeholder => "Ex: http://organization.com" %>
  <%= f.submit %>
<% end %>

app/views/organizations/edit.html.erb
<div class="org-edit-page">
  <h2>Edit Organization: <%= @organization.name %></h2>
  <h3><%= link_to "Back to Coalition List", organizations_path %></h3>

  <div class="form">
    <%=render 'neworg' %>
  </div>
</div>

app/views/organizations/index.html.erb
<% if current_user %>
<div>
  <h3>Welcome, <%= @user.email %>!</h3>
  <%= link_to "Sign Out", destroy_user_session_path, :method => :delete, :class => "btn btn-danger" %>
  <%= link_to "Back to Admin Portal", "/admin", :class => "btn btn-primary" %>
</div>
<% end %>

<h2>List of Coalition Members</h2>
<%= link_to "Add New Member", new_organization_path, :class => "btn btn-lg btn-primary" %>

<ul class="admin-org-list">
  <% @organizations.each do |org| %>
    <li class="each">
      <span class="admin-org-name-link">
        <%= link_to "#{org.name}", org.orgUrl %>
      </span>
      <span class="admin-org-type">Type: <%= org.orgtype %></span>
      <span class="admin-edit-delete">
        <div class="edit">
          <%= link_to "Edit Organization", edit_organization_path(org), :class => "btn btn-sm btn-default" %>
        </div>
        <div class="delete">
          <%= form_for(org, method: :delete) do |f| %>
            <%= f.submit "Delete Organization", :class => "btn btn-sm btn-danger" %>
          <% end %>
        </div>
      </span>
    </li>
  <% end %>
</ul>

app/views/organizations/new.html.erb
<div class="org-new-page">
  <h2>Add Organization to Coalition List</h2>
  <h3><%= link_to "Back to Coalition List", organizations_path %></h3>

  <div class="form">
    <%=render 'neworg' %>
  </div>

</div>